name: learn-github-actions
run-name: l-Git-A [${{ github.ref }}]
# on: [push]
on:
  workflow_dispatch:
    inputs:
      test_version_alias:
        type: string
        required: false
        description: Docker image version of the test environment.
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen"
      - uses: actions/checkout@v2
      - run: |
          ls -al
          cd .github/workflows/
          ls -al