name: learn-github-actions
run-name: l-Git-A [${{ github.ref }}]
# on: [push]
on:
  workflow_dispatch:
    inputs:
      test_version_alias:
        type: string
        required: false
        description: Docker image version of the test environment.
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
      - uses: actions/checkout@v2
      - run: |
          ls -al
          cd .github/workflows/
          ls -al